apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8shserver
  name: k8shserver
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9090
    name: http
  selector:
    app: k8shserver
  type: LoadBalancer
